extends:
  - airbnb
  - prettier
parser: babel-eslint
plugins:
    - prettier
    - react
    - jsx-a11y
    - import
env:
  browser: true
  node: true
  jest: true
rules:
  no-plusplus: off
  react/jsx-closing-bracket-location: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  import/extensions: off
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
  react/forbid-prop-types: off
  jsx-a11y/anchor-is-valid: off
  no-underscore-dangle: off
  # no-console: off  # switch rule off for Node.js
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  max-len: off
  